[versions]
adsIdentifier = "3.4.62.300"
adsIdentifierVersion = "1.0.2.301"
agp = "9.4.0"
android_cn_oaidVersion = "4.2.17"
comGoogleCodeGsonGson = "2.14.0"
coreSplashscreenVersion = "1.2.0"
glide = "5.0.9"
core = "3.5.4"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.8.0"
lifecycleViewmodel = "2.11.0"
lifecycleLivedata = "2.11.0"
materialVersion = "1.14.0"
activity = "1.13.0"
constraintlayout = "2.2.2"
okhttp = "5.5.0"
sensebot = "4.4.4"
touchimageview = "3.7.2"
ucrop = "2.2.11"

kotlin = "2.4.10"
hilt = "2.60.1"

datastoreRx = "1.2.1"
rxjava3 = "3.1.12"

[libraries]
ads-identifier = { module = "com.huawei.hms:ads-identifier", version.ref = "adsIdentifier" }
com-google-code-gson-gson3 = { module = "com.google.code.gson:gson", version.ref = "comGoogleCodeGsonGson" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreenVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gzu-liyujiang-android_cn_oaid = { module = "com.github.gzu-liyujiang:Android_CN_OAID", version.ref = "android_cn_oaidVersion" }
com-google-zxing-core = { module = "com.google.zxing:core", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycleLivedata" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mcs-ads-identifier = { module = "com.hihonor.mcs:ads-identifier", version.ref = "adsIdentifierVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
sensebot = { module = "com.geetest.sensebot:sensebot", version.ref = "sensebot" }
touchimageview = { module = "com.github.MikeOrtiz:TouchImageView", version.ref = "touchimageview" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
datastore-preferences-rxjava3 = { group = "androidx.datastore", name = "datastore-preferences-rxjava3", version.ref = "datastoreRx" }
rxjava3 = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

